version: "3.8"

services:
  fastapi:
    image: pytocompany/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      ENV: "production"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MISTRAL_AI_API_KEY: ${MISTRAL_AI_API_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      PATH_TO_MODELS: /app/models/
      PATH_TO_LOGS: /app/logs
    volumes:
      - ./static:/app/static
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    expose:
      - "5432"  # Internal communication only
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
