name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        env:
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag Docker image
      - name: Build Docker image
        run: docker build -t fastapi .

      - name: Tag Docker image
        run: docker tag fastapi pytocompany/fastapi:latest

      # Push Docker image to registry
      - name: Push Docker image to DockerHub
        run: docker push pytocompany/fastapi:latest

  deploy_models:
    name: Deploy AI Models
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes in ai_models
        id: check_changes
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep ^ai_models/ || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Copy AI models to server
        if: steps.check_changes.outputs.changed != ''
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ai_models/*"
          target: ${{ vars.PATH_TO_MODELS }}
          strip_components: 1

  deploy:
    name: Deploy on AlmaLinux Server
    needs: [build_and_push, deploy_models]
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy docker-compose.yml to the server
      - name: Copy docker-compose.yml to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./docker-compose.yml
          target: /var/www/pyto_project

      # SSH into the server and deploy
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/pyto_project &&
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USER }} --password-stdin &&
            export DATABASE_USER="${{ vars.DATABASE_USER }}" &&
            export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" &&
            export DATABASE_NAME="${{ vars.DATABASE_NAME }}" &&
            export DATABASE_HOST="${{ vars.DATABASE_HOST }}" &&
            export DATABASE_PORT="${{ vars.DATABASE_PORT }}" &&
            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" &&
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" &&
            export MISTRAL_AI_API_KEY="${{ secrets.MISTRAL_AI_API_KEY }}" &&
            export OPEN_WEATHER_API_KEY="${{ secrets.OPEN_WEATHER_API_KEY }}" &&
            export PATH_TO_MODELS="${{ vars.PATH_TO_MODELS }}" &&
            echo 'starting down' &&
            docker-compose down &&
            echo 'starting pull' &&
            docker-compose pull &&
            echo 'starting up' &&
            docker-compose up -d &&
            mv docker-compose.yml docker-compose-$(date +"%Y%m%d%H%M%S").yml